### ISSUE TITLE
High resolution display issue

### ISSUE THREAD

**Issue by nricciardi** [VirtualCable/openuds#111] opened 2024-03-01 21:15 UTC
I have a high resolution display (2560x1600, yes, it is 16:10). I have Linux Mint and I installed UDS client from `.deb`.

When I run UDS client there is a problem: UI elements are smalls. I fixed this problem in Mint using monitor scale (to 150%), but this are not used from UDS client.

If I change manually Mint monitor resolution (e.g. 1920x1200) there are not problems, but how can I fix my resolution problems without change resolution? Can I force a specific resolution in UDS client?

**Comment by dkmstr** [comment] 2024-03-02 04:32
You can alter the freerdp (is rdp, isn't it?) parameters used from the transport itself... Under normal circunstancies the local resolution is transferred by RDP client (freerdp in case of Linux), and used by remote desktop, but some tuning can be made: 

Take a look at the freerdp parameters:
    /scale:[100|140|180]              Scaling factor of the display
    /scale-desktop:<percentage>       Scaling factor for desktop applications
    /scale-device:100|140|180         Scaling factor for app store applications

The client itself uses freerdp. You can use them on the transport, under the "linux client" tab, on the "Custom parameters" field.

Hope this helps.

**Comment by nricciardi** [comment] 2024-03-02 08:52
It should be RDP protocol, but I'm not 100% sure (I'm using a virtual machine hosted by my university).

I installed UDS client (a python project, isn't it?), how can I manage those parameters? How can I run from terminal the client?

**Comment by dkmstr** [comment] 2024-03-02 16:36
No, the parameters are set from the administration interface only sorry, and the part that executes it locally, is a signed script that will not work if modified (also, can only be modified anyway from admin part, and even that is not possible..)

**Comment by nricciardi** [comment] 2024-03-02 18:10
So, there are no ways to fix resolution not being administrator?

**Comment by dkmstr** [comment] 2024-03-02 18:30
Asking one to create a profile for your kind of device, or reducing your local display size... :(

Sorry, but this is designed to limit as much as we can user capabilities to alter connections definition by design... :(

UDS is a broker, where administrators defines, at all levels, what users can do. Letting "normal" (not you, but a "normal" user) change properties (what was possible a long time ago on UDS), generates LOTS of incidences on UDS administrators, so about 6 or 8 years ago, we decided to remove that capacity. 

Now, if you want something, the platform administrator must provide it.

Again, sorry id this dislikes you.

Regards,

**Closed** 2024-03-02 18:30 UTC
